export const homeObjOne = {
	id: 'home',
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Covid -19 UPdate',
	headLine: 'blah blah blah',
	description: 'We are open for indoor and outdoor dining everyday 4 - 10 ish. Take out available.',
	buttonLabel: 'Menu',
	imgStart: true,
	img: require('../../images/paolo.png'),
	alt: 'picture',
	dark: true,
	primary: false,
	darkText: false,
}

export const homeObjTwo = {
	id: 'menu',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Menu',
	headLine: 'blah blah blah',
	description: 'this is where the menu goes',
	buttonLabel: 'Home',
	imgStart: true,
	img: require('../../images/paolo.png'),
	alt: 'picture',
	dark: false,
	primary: false,
	darkText: true,
}

export const homeObjThree = {
	id: 'about',
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Hours and Reservations',
	headLine: '504 NW 9th Ave Portland, Oregon 97209. ',
	description: 'more blahh blah fucking blah',
	buttonLabel: 'Menu',
	imgStart: true,
	img: require('../../images/paolo.png'),
	alt: 'picture',
	dark: true,
	primary: false,
	darkText: false,
}